application: ""
application_tagline: ""
application_description: "Description Goes here"

mail:
  from: ""
  support_email: ""
  no_reply: ""
  contact: ""


photo:
  missing_thumb: 'icon_missing_thumb.gif'
  missing_medium: "icon_missing_medium.gif"
  paperclip_options:
    resize_to: "465>"
    min_size: 1
    #size in megabytes
    max_size: 3
    style: {thumb: "100x100", medium: "290x320", large: "664>", tiny: "50x50"}
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 'filesystem'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']
    path_prefix: 'public/uploads'


# NOTE: When ever you are declaring a new controller make sure you define the name of the controller in the below mentioned list.
reserved_logins: [
  'about',
  'account',
  'advertise',
  'ads',
  'application',
  'assets',
  'categories',
  'choices',
  'clippings',
  'clipping_images',
  'comments',
  'contests',
  'countries',
  'css_help',
  'events',
  'favorites',
  'faq',
  'featured',
  'forums',
  'friendships',
  'friendship_statuses',
  'home',
  'homepage_features',
  'images',
  'invitations',
  'javascripts',
  'login',
  'logout',
  'manage_photos',
  'messages',
  'metro_areas',
  'moderatorships',
  'new_clipping',
  'offerings',
  'photos',
  'polls',
  'popular',
  'popular_rss',
  'posts',
  'recent',
  'roles',
  'search',
  'signup',
  'sb_posts',
  'skills',
  'sitemap',
  'states',
  'stylesheets',
  'tags',
  'theme',
  'topics',
  'users',
  'votes']
